import {
    RESULT_CODE_REJECT_WITH_SECURITY,
    RESULT_CODE_REJECT_WITH_WRONG_CREDENTIAL,
    RESULT_CODE_SUCCESS,
} from "../constants/apiResultCodeConstans";

export type ResultCodeTypes =
    | typeof RESULT_CODE_SUCCESS
    | typeof RESULT_CODE_REJECT_WITH_SECURITY
    | typeof RESULT_CODE_REJECT_WITH_WRONG_CREDENTIAL;
