name: Deploy to Dev

on:
  push:
    branches: [development]

jobs:
  checks:
    name: Verify Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: checks

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Deploy to Dev
        run: |
          npm install -g netlify-cli
          netlify deploy \
          --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} \
          --site ${{ secrets.NETLIFY_DEV_SITE_ID }} \
          --prod \
          --dir=dist \
          --message="Deploy from ${{ github.ref_name }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEV_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}
