name: Preview

on:
  pull_request:

jobs:
  preview:
    name: Deploy Preview to Netlify
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: npm ci
      - run: npm run build
      - name: Deploy Preview
        run: |
          npm install -g netlify-cli
          netlify deploy \
          --auth $NETLIFY_AUTH_TOKEN \
          --site $NETLIFY_SITE_ID \
          --dir=dist \
          --message="Preview from PR #${{ github.event.pull_request.number }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
